### ISSUE TITLE
How to add default filter for dynamic filter

### ISSUE THREAD

**Issue by amit-siddhu** [bogdan/datagrid#140]
Hi Bogdan,
                 I have a filter named dynamic filter, now i want to apply one of it by default on a value like:
``status != 'Done'`` , if i add this in the scope than it never show rows with 'Done' status. status is one of the option in dynamic filter.

**Comment by bogdan** [comment]
I am not sure how did you add the `!=` support to dynamic filter. Can you show the source code of what you have currently?

**Comment by amit-siddhu** [comment]
yes, there is no any operator like != , and i do not want to add this, i just want to by default display the records whose status != 'Done', but user can always apply status = 'Done' , to filter records whose status is Done.

**Comment by bogdan** [comment]
Maybe this is what you want:  

``` ruby
 filter(:condition, :dynamic, allow_blank: true, allow_nil: true) do |(field, operation, value), scope|
    unless value.blank?
      scope.where(
        "#{field} #{operation} ?", value
      )
    else
      scope.where.not(status: 'Done')
    end
  end
```

`allow_blank` and `allow_nil` give you the control how filter works when filter value is blank or nil.

**Comment by amit-siddhu** [comment]
Not working :( 
```ruby
filter(:condition, :dynamic, :header => "Dynamic filter", allow_blank: true, allow_nil: true, :select => [["Jira","jira"],["Status","status"],["Dev start date","dev_start"]]) do |(field, operation, value), scope|
    unless value.blank?
      scope.where(
        "#{field} #{operation} ?", value
      )
    else
      scope.where.not(status: 'Done')
    end
  end
```
main grid scope:
```ruby
scope do
    Release.where('status != ?', 'deleted').order(created_at: :desc)
  end
```

**Comment by bogdan** [comment]
There is truly a bug with this option combination. I've fixed it in master:
https://github.com/bogdan/datagrid/commit/dd5794c5de6b89a5ae938833788a43a689a972f9

Can you check if it works from master for you?

**Comment by amit-siddhu** [comment]
i am using datagrid version 1.3.4 now, but still not working.

**Comment by bogdan** [comment]
You need to use it from master because latest patch is not released yet. Add the following to gemfile:

```
gem 'datagrid', github: 'bogdan/datagrid', branch: 'master'
```

and run `bundle update datagrid`

**Comment by amit-siddhu** [comment]
still not working

**Comment by bogdan** [comment]
Here is code I'am testing with:

``` ruby
class TestGrid
  
  include Datagrid 

  # The model from my project
  scope {Offer} 

  filter(:condition, :dynamic, allow_nil: true, allow_blank: true) do |(field, operation, value), scope|
    unless value.blank?
      if operation == '=~'
        operation = 'like' # like on mysql and ilike on postgresql
        value = "%#{value}%"
      end
      scope.where("#{field} #{operation} ?", value)
    else
      scope.where.not(status: 'Done')
    end
  end
end

puts TestGrid.new.assets.to_sql
```

It returns `SELECT `offers`.* FROM `offers`  WHERE (`offers`.`status` != 'Done')`

Can you make your example like that?

**Comment by amit-siddhu** [comment]
many thanks!! Bogdan! for dd5794c and also for:


```ruby
if operation == '=~'
        operation = 'like' # like on mysql and ilike on postgresql
        value = "%#{value}%"
      end
```

now my task is to detect database and use appropriate operator.
Actually i forgot to include ```allow_nil: true, allow_blank: true``` after updating datagrid to master.

**Comment by amit-siddhu** [comment]
adapter_type = connection.adapter_name.downcase.to_sym
case adapter_type
when :mysql
  operation = 'like'
when :sqlite
 operation = 'like'
when :postgresql
  operation = 'ilike'
end

**Comment by bogdan** [comment]
There is a way to use arel to that already builds abstraction on top of `like`.

Check this link: `http://stackoverflow.com/questions/4430578/how-to-do-a-like-query-in-arel-and-rails-3`

**Comment by amit-siddhu** [comment]
thanks for sharing this stackoverflow !! great answer by Padro!
